services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=nFErT3qmyXSFa0
      - MINIO_ROOT_PASSWORD=CI4hvrjJQiS3NuNi4nMHPVBqzHU8Bw0
    volumes:
      - minio_data:/data
  app:
    depends_on:
      - minio
    build: .
    ports:
      - 10000:10000
    env_file:
      - .env
      
volumes:
  minio_data: